### ISSUE TITLE
1.16.4

### ISSUE THREAD

**Issue by 0ddlyoko** [barneygale/quarry#102]
When will quarry be updated to 1.16.4 ?

Thanks :)

**Comment by barneygale** [comment]
Packet list looks unchanged - why do Mojang insist on bumping the protocol version nowadays?!

Should be fixed in eb1457cc1ae19b971282db3defea609f2b8375a5. I haven't yet published a new version to PyPI as there's some docs updates needed for other changes. Can you test it out? If you're using pip, something like `pip install --upgrade -e git+https://github.com/barneygale/quarry.git` should do the trick.
